service: cadastro-pacientes

frameworkVersion: '2'

plugins:
  # npm i serverless-dynamodb-local --save-dev && sls dynamodb install ; //to download a DynamoDBLocal.jar
  - serverless-dynamodb-local
  - serverless-offline

# default values https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
provider:
  name: aws
  runtime: nodejs12.x
  # opt é se algo for inserido via linha de comando $ sls offline start --stage dev
  stage: ${opt:stage, 'dev'}
  apiName: ${self:provider.stage, 'dev'}
  region: us-east-1
  # mantain 20201221 default version of hashing algorithm
  lambdaHashingVersion: 20201221
  environment:
   PACIENTES_TABLE: 'PACIENTES-${self:provider.stage}'
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PACIENTES_TABLE}'

functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: pacientes
          method: get

  obterPaciente:
    handler: handler.obterPaciente
    events:
      - http:
          path: pacientes/{pacienteId}
          method: get

  cadastrarPaciente:
    handler: handler.cadastrarPaciente
    events:
      - http:
          path: pacientes
          method: post

  atualizarPaciente:
    handler: handler.atualizarPaciente
    events:
      - http:
          path: pacientes/{pacienteId}
          method: put
          
  excluirPaciente:
    handler: handler.excluirPaciente
    events:
      - http:
          path: pacientes/{pacienteId}
          method: delete


resources:
  Resources:
    PacientesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PACIENTES_TABLE}
        AttributeDefinitions:
          - AttributeName: paciente_id
            AttributeType: S
        KeySchema:
          - AttributeName: paciente_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      domain:
        sources:
          - table: ${self:provider.environment.PACIENTES_TABLE}
            sources: [./offline/migrations/pacientes-seed.json]
